name: 'Build'
on:
  push:
    branches:
      - master
jobs:
  build:
    uses: chorizite/github-workflows/.github/workflows/build-gitversion.yml@master
    permissions:
      packages: write
      contents: write
    with:
      package_id: Chorizite.Plugins.Lua
      plugin_bin_dir: "${{ github.workspace }}/bin/net8.0"
    secrets:
      access_token: ${{ github.ACCESS_TOKEN }}
